version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "oracleinanutshell/oracle-xe-11g"
    environment:
      - ORACLE_PWD=oracle
    ports:
      - "1521:1521"
